services:
  - type: web
    name: churn-prediction
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: python -m gunicorn churn_project.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
